# Generated by Django 4.0.2 on 2022-02-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_userdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='box_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
