# Generated by Django 4.0.2 on 2022-02-19 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_userdata_box_status_alter_userdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='due_date',
            field=models.DateField(default=datetime.date(2022, 2, 19)),
        ),
    ]
