# Generated by Django 4.0.2 on 2022-02-20 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_userdata_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2022, 2, 20, 11, 58, 15, 247014)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='due_date',
            field=models.DateField(default=datetime.time(11, 58, 15, 247014)),
        ),
    ]
